import Foundation

public enum ShellIntegrationInstaller {
    public static func prepare(
        at directory: URL,
        tmuxCapabilities: TmuxCapabilities = .modernFallback
    ) throws {
        try FileManager.default.createDirectory(
            at: directory,
            withIntermediateDirectories: true,
            attributes: [.posixPermissions: 0o700]
        )

        let integrationURL = directory.appendingPathComponent("apexterm-integration.zsh")
        try writeIfChanged(zshIntegration, to: integrationURL, permissions: 0o600)
        try writeIfChanged(
            tmuxConfiguration(capabilities: tmuxCapabilities),
            to: tmuxConfigurationURL(at: directory),
            permissions: 0o600
        )

        for file in [".zshenv", ".zprofile", ".zlogin", ".zlogout"] {
            try writeIfChanged(
                passthroughWrapper(for: file),
                to: directory.appendingPathComponent(file),
                permissions: 0o600
            )
        }

        try writeIfChanged(
            zshRCWrapper,
            to: directory.appendingPathComponent(".zshrc"),
            permissions: 0o600
        )
    }

    public static func tmuxConfigurationURL(at directory: URL) -> URL {
        directory.appendingPathComponent("tmux.conf")
    }

    public static func environmentDictionary(
        wrapperDirectory: URL,
        base: [String: String] = ProcessInfo.processInfo.environment
    ) -> [String: String] {
        var environment = base
        let originalZDOTDIR = environment["ZDOTDIR"]
            .map { NSString(string: $0).expandingTildeInPath }
            ?? environment["HOME"]
            ?? FileManager.default.homeDirectoryForCurrentUser.path

        environment["APEXTERM_ORIGINAL_ZDOTDIR"] = originalZDOTDIR
        environment["APEXTERM_SHELL_INTEGRATION"] = "1"
        environment["ZDOTDIR"] = wrapperDirectory.path
        environment["TERM"] = "xterm-256color"
        environment["COLORTERM"] = "truecolor"
        environment["TERM_PROGRAM"] = "ApexTerm"
        environment["TERM_PROGRAM_VERSION"] = "0.1.0"
        if environment["LANG"] == nil {
            environment["LANG"] = "en_US.UTF-8"
        }

        return environment
    }

    public static func environment(
        wrapperDirectory: URL,
        base: [String: String] = ProcessInfo.processInfo.environment
    ) -> [String] {
        environmentDictionary(wrapperDirectory: wrapperDirectory, base: base)
            .sorted { $0.key < $1.key }
            .map { "\($0.key)=\($0.value)" }
    }

    private static func passthroughWrapper(for filename: String) -> String {
        """
        # Generated by ApexTerm. User files remain in APEXTERM_ORIGINAL_ZDOTDIR.
        if [[ -n "${APEXTERM_ORIGINAL_ZDOTDIR:-}" && -r "$APEXTERM_ORIGINAL_ZDOTDIR/\(filename)" ]]; then
          source "$APEXTERM_ORIGINAL_ZDOTDIR/\(filename)"
        fi
        """
    }

    private static let zshRCWrapper = """
    # Generated by ApexTerm. User files remain in APEXTERM_ORIGINAL_ZDOTDIR.
    if [[ -n "${APEXTERM_ORIGINAL_ZDOTDIR:-}" && -r "$APEXTERM_ORIGINAL_ZDOTDIR/.zshrc" ]]; then
      source "$APEXTERM_ORIGINAL_ZDOTDIR/.zshrc"
    fi
    source "${ZDOTDIR}/apexterm-integration.zsh"
    """

    public static func tmuxConfiguration(
        capabilities: TmuxCapabilities
    ) -> String {
        var lines = [
            "# Generated by ApexTerm. tmux owns scrollback while its alternate screen is active.",
            "set-option -g mouse on",
            "set-option -g history-limit 50000",
            "set-option -g focus-events on"
        ]

        if capabilities.supportsTerminalFeatures {
            lines.append(
                "set-option -sa terminal-features \",xterm-256color:RGB:extkeys\""
            )
        } else {
            lines.append(
                "set-option -ga terminal-overrides \",xterm-256color:Tc\""
            )
        }
        if capabilities.supportsExtendedKeys {
            lines.append("set-option -s extended-keys on")
        }
        if capabilities.supportsExtendedKeysFormat {
            lines.append("set-option -s extended-keys-format csi-u")
        }
        if capabilities.supportsAllowPassthrough {
            lines.append("set-option -g allow-passthrough on")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private static let zshIntegration = #"""
    # ApexTerm semantic shell integration. It emits lifecycle and command markers.
    if [[ -z "${APEXTERM_SHELL_INTEGRATION_ACTIVE:-}" ]]; then
      typeset -g APEXTERM_SHELL_INTEGRATION_ACTIVE=1
      typeset -g _APEXTERM_COMMAND_RUNNING=0

      # OSC lifecycle markers intentionally do not print a newline. Disable zsh's
      # partial-line marker so a stray '%' is not captured as command output.
      typeset -g PROMPT_EOL_MARK=''

      autoload -Uz add-zsh-hook

      function _apexterm_osc133() {
        local payload="${1//$'\a'/}"
        payload="${payload//$'\e'/}"
        if [[ -n "${TMUX:-}" ]]; then
          printf '\ePtmux;\e\e]%s\a\e\\' "${payload}"
        else
          printf '\e]%s\a' "${payload}"
        fi
      }

      function _apexterm_precmd() {
        local command_status=$?
        printf '\e[0m'
        if [[ "${_APEXTERM_COMMAND_RUNNING}" == "1" ]]; then
          _apexterm_osc133 "133;D;${command_status}"
          typeset -g _APEXTERM_COMMAND_RUNNING=0
        fi
        _apexterm_osc133 '133;A'
      }

      function _apexterm_preexec() {
        local apexterm_command="${1//$'\a'/}"
        apexterm_command="${apexterm_command//$'\e'/}"
        printf '\e[0m'
        _apexterm_osc133 "133;E;${apexterm_command}"
        _apexterm_osc133 '133;C'
        printf '%s' "${APEXTERM_OUTPUT_ANSI:-}"
        typeset -g _APEXTERM_COMMAND_RUNNING=1
      }

      add-zsh-hook precmd _apexterm_precmd
      add-zsh-hook preexec _apexterm_preexec

      # Marker B is placed before the prompt. The final color applies to typed input.
      if [[ -n "${TMUX:-}" ]]; then
        typeset -g _APEXTERM_PROMPT_MARKER_B=$'\ePtmux;\e\e]133;B\a\e\\'
      else
        typeset -g _APEXTERM_PROMPT_MARKER_B=$'\e]133;B\a'
      fi
      PROMPT=$'%{'"${_APEXTERM_PROMPT_MARKER_B}"$'%}'"${PROMPT}"$'%{'"${APEXTERM_INPUT_ANSI:-}"$'%}'
    fi
    """#

    private static func writeIfChanged(
        _ content: String,
        to url: URL,
        permissions: Int
    ) throws {
        let data = Data(content.utf8)
        if let existing = try? Data(contentsOf: url), existing == data {
            try? FileManager.default.setAttributes(
                [.posixPermissions: permissions],
                ofItemAtPath: url.path
            )
            return
        }
        try data.write(to: url, options: [.atomic])
        try FileManager.default.setAttributes(
            [.posixPermissions: permissions],
            ofItemAtPath: url.path
        )
    }
}
